### ISSUE TITLE
Unpickling error when loading default model

### ISSUE THREAD

**Issue by guillemcortes** [merlresearch/cocktail-fork-separation#1]
Hi,

Love your work and thank you for sharing the code, really awesome.

I'm facing some issues while trying to run a dummy separation like  python3.9 separate.py --audio-path _audio_ --out-dir _outdir_

I copy the Traceback:
```
Traceback (most recent call last):
  File "/git/cocktail-fork-separation/separate.py", line 165, in <module>
    cli_main()
  File "/git/cocktail-fork-separation/separate.py", line 161, in cli_main
    separate_soundtrack_file(args.audio_path, output_dir, device=device, consistency_mode=args.mixture_residual)
  File "/git/cocktail-fork-separation/separate.py", line 124, in separate_soundtrack_file
    output_dict = separate_soundtrack(
  File "/git/cocktail-fork-separation/separate.py", line 82, in separate_soundtrack
    separation_model = load_default_pre_trained()
  File "/git/cocktail-fork-separation/separate.py", line 22, in load_default_pre_trained
    state_dict = torch.load(DEFAULT_PRE_TRAINED_MODEL_PATH)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

And also the pip freeze output:
```
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==22.2.0
certifi==2019.11.28
chardet==3.0.4
charset-normalizer==3.0.1
dbus-python==1.2.16
distro-info===0.23ubuntu1
frozenlist==1.3.3
fsspec==2023.1.0
future==0.18.3
idna==2.8
lightning-utilities==0.6.0.post0
multidict==6.0.4
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
packaging==23.0
PyGObject==3.36.0
pyloudnorm==0.1.1
python-apt==2.0.1
pytorch-lightning==1.9.0
PyYAML==6.0
requests==2.22.0
requests-unixsocket==0.2.0
scipy==1.10.0
six==1.14.0
torch==1.13.1
torchaudio==0.13.1
torchmetrics==0.11.1
tqdm==4.64.1
typing-extensions==4.5.0
unattended-upgrades==0.1
urllib3==1.25.8
yarl==1.8.2
```

Can you help me with this?

Many thanks.

**Comment by darius522** [comment]
Hi Guillem - Thank you for the kind words. 

With a fresh `pip install -r requirements.txt` I was not able to reproduce your error. However, I am noticing that your `torch`, `torchaudio`, and `pytorch-lightning` versions diff from the `requirements.txt`:

Could you possibly try again from a new environment and by installing the above, see if that works ?

Thanks,-
-Darius

**Comment by darius522** [comment]
Hey Guillem - Your environment looks good to me. After a bit of search, it looks like this issue emerges when the `.pth` file has not been properly and/or fully downloaded. That sometimes happen with large files on `git`. Could you try to manually download the files in the `checkpoints` directory and give it another try ?

Thanks!
Darius

**Comment by guillemcortes** [comment]
Sure, I'll let you know.

Thanks!

**Comment by gwichern** [comment]
@guillemcortes - I think this is git lfs related. We just enabled the setting so that git lfs assets are included when you download the repo as a zip archive. Please ensure you have git lfs installed and reclone, or redownload the zip archive. You should also be able to manually download the checkpoint files as Darius suggested.

**Comment by guillemcortes** [comment]
Manually downloading the .pth files worked, thanks!
